export const mockData = {
  accountListId: '123456789',
  accountName: 'Test Account',
  funds: {
    staffAccount: {
      balance: 15000,
      pending: 17500,
    },
    staffConferenceSavings: {
      balance: 500,
      pending: 200,
    },
    staffSavings: {
      balance: 2500,
      pending: 0,
    },
  },
  history: [
    {
      transfers: 'staffSavings to staffAccount',
      amount: 2500,
      schedule: 'One Time',
      status: 'Pending',
      transferDate: '2023-09-26',
      stopDate: '',
      note: 'Reimbursements',
      actions: 'dropdown',
    },
    {
      transfers: 'staffAccount to staffSavings',
      amount: 1200,
      schedule: 'Monthly',
      status: 'Ongoing',
      transferDate: '2023-09-30',
      stopDate: '2025-09-30',
      note: 'Long-term savings',
      actions: 'edit-pause',
    },
    {
      transfers: 'staffSavings to staffAccount',
      amount: 500,
      schedule: 'One Time',
      status: 'Complete',
      transferDate: '2023-09-29',
      stopDate: '',
      note: 'Tax',
      actions: 'dropdown',
    },
    {
      transfers: 'staffAccount to staffConferenceSavings',
      amount: 120,
      schedule: 'Monthly',
      status: 'Ended',
      transferDate: '2023-09-28',
      stopDate: '2024-06-01',
      note: 'Cru 25',
      actions: 'dropdown',
    },
    {
      transfers: 'staffAccount to staffConferenceSavings',
      amount: 750,
      schedule: 'One Time',
      status: 'Failed',
      transferDate: '2023-09-27',
      stopDate: '',
      note: 'X-fer tickets',
      actions: 'dropdown',
    },
  ],
};
