codecov:
  notify:
    # Github actions is running 12 test jobs so wait until all those have finished
    after_n_builds: 12

coverage:
  status:
    project:
      default:
        target: 80%

comment: false
