codecov:
  notify:
    # Github actions is running 8 test jobs so wait until all those have finished
    after_n_builds: 8

coverage:
  status:
    project:
      default:
        target: 80%

comment: false
