plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - x86
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
    - win32
    
yarnPath: .yarn/releases/yarn-3.8.1.cjs
