'project_id': '813672'
'api_token_env': CROWDIN_API_TOKEN
'base_path': '.'
'base_url': 'https://api.crowdin.com'
'pull_request_labels': ['crowdin']
'pull_request_reviewers': ['dr-bizz', 'canac']
'preserve_hierarchy': true
files:
  [
    {
      'source': 'public/locales/en/translation.json',
      'translation': 'public/locales/%two_letters_code%/translation.json',
    },
  ]
