import { renderHook } from '@testing-library/react-hooks';
import { StatusEnum } from 'src/graphql/types.generated';
import { CurrencyTable } from './FourteenMonthReport';
import { Contact } from './Layout/Table/TableHead/TableHead';
import { useCsvData } from './useCsvData';

const mockContact = (mocks?: Partial<Contact>): Contact => ({
  id: 'contact-1',
  name: 'Test Contact',
  total: 100,
  average: 25,
  minimum: 50,
  completeMonthsTotal: 100,
  accountNumbers: ['12345'],
  lateBy30Days: false,
  lateBy60Days: false,
  pledgeAmount: 100,
  pledgeCurrency: 'USD',
  pledgeFrequency: 'Monthly',
  status: 'PARTNER_FINANCIAL',
  months: [
    {
      month: '2021-01',
      total: 25,
      salaryCurrencyTotal: 25,
      donations: [
        {
          amount: 25,
          date: '2021-01-15',
          paymentMethod: 'Check',
          currency: 'USD',
        },
      ],
    },
  ],
  ...mocks,
});

describe('useCsvData', () => {
  it('generates CSV data', async () => {
    const tables: CurrencyTable[] = [
      {
        currency: 'USD',
        totals: [
          { total: 100, month: '2020-12-01' },
          { total: 200, month: '2020-11-01' },
          { total: 150, month: '2020-10-01' },
          { total: 100, month: '2020-09-01' },
          { total: 200, month: '2020-08-01' },
          { total: 150, month: '2020-07-01' },
          { total: 100, month: '2020-06-01' },
          { total: 200, month: '2020-05-01' },
          { total: 150, month: '2020-04-01' },
          { total: 100, month: '2020-03-01' },
          { total: 200, month: '2020-02-01' },
          { total: 150, month: '2020-01-01' },
          { total: 100, month: '2019-12-01' },
          { total: 200, month: '2019-11-01' },
        ],
        orderedContacts: [
          // Partner pledged for $450/quarter but who gave $275/month average over the last quarter
          mockContact({
            name: 'Quarterly Partner',
            status: StatusEnum.PartnerFinancial,
            pledgeAmount: 450,
            pledgeCurrency: 'USD',
            pledgeFrequency: '3.0',
            months: [
              {
                total: 0,
                month: '2020-12-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 350,
                month: '2020-11-01',
                salaryCurrencyTotal: 350,
                donations: [],
              },
              {
                total: 300,
                month: '2020-10-01',
                salaryCurrencyTotal: 300,
                donations: [],
              },
              {
                total: 250,
                month: '2020-09-01',
                salaryCurrencyTotal: 250,
                donations: [],
              },
              {
                total: 200,
                month: '2020-08-01',
                salaryCurrencyTotal: 200,
                donations: [],
              },
              {
                total: 0,
                month: '2020-07-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-06-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-05-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-04-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-03-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-02-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2020-01-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2019-12-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 0,
                month: '2019-11-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
            ],
          }),

          // Partner pledged for $1200/year but who gave $75/month average over the last quarter
          mockContact({
            name: 'Annual Partner',
            status: StatusEnum.PartnerFinancial,
            pledgeAmount: 1200,
            pledgeCurrency: 'USD',
            pledgeFrequency: '12.0',
            months: [
              {
                total: 0,
                month: '2020-12-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 100,
                month: '2020-11-01',
                salaryCurrencyTotal: 100,
                donations: [],
              },
              {
                total: 0,
                month: '2020-10-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 200,
                month: '2020-09-01',
                salaryCurrencyTotal: 200,
                donations: [],
              },
              {
                total: 0,
                month: '2020-08-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 100,
                month: '2020-07-01',
                salaryCurrencyTotal: 100,
                donations: [],
              },
              {
                total: 0,
                month: '2020-06-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 200,
                month: '2020-05-01',
                salaryCurrencyTotal: 200,
                donations: [],
              },
              {
                total: 0,
                month: '2020-04-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 100,
                month: '2020-03-01',
                salaryCurrencyTotal: 100,
                donations: [],
              },
              {
                total: 0,
                month: '2020-02-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 200,
                month: '2020-01-01',
                salaryCurrencyTotal: 200,
                donations: [],
              },
              {
                total: 0,
                month: '2019-12-01',
                salaryCurrencyTotal: 0,
                donations: [],
              },
              {
                total: 100,
                month: '2019-11-01',
                salaryCurrencyTotal: 100,
                donations: [],
              },
            ],
          }),
        ],
      },
      {
        currency: 'CAD',
        totals: [
          { total: 100, month: '2020-03-01' },
          { total: 200, month: '2020-02-01' },
          { total: 150, month: '2020-01-01' },
        ],
        orderedContacts: [],
      },
    ];
    const { result } = renderHook(() => useCsvData(tables), {});

    expect(result.current).toEqual([
      ['Currency', 'USD', '$'],
      [
        'Partner',
        'Status',
        'Commitment Amount',
        'Commitment Currency',
        'Commitment Frequency',
        'Committed Monthly Equivalent',
        'In Hand Monthly Equivalent',
        'Missing In Hand Monthly Equivalent',
        'In Hand Special Gifts',
        'In Hand Date Range',
        'Dec 20',
        'Nov 20',
        'Oct 20',
        'Sep 20',
        'Aug 20',
        'Jul 20',
        'Jun 20',
        'May 20',
        'Apr 20',
        'Mar 20',
        'Feb 20',
        'Jan 20',
        'Dec 19',
        'Nov 19',
        'Total (last month excluded from total)',
      ],
      [
        'Quarterly Partner',
        'Partner - Financial',
        450,
        'USD',
        'Quarterly',
        150,
        150,
        -0,
        500,
        'Aug 20 - Nov 20',
        0,
        350,
        300,
        250,
        200,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        100,
      ],
      [
        'Annual Partner',
        'Partner - Financial',
        1200,
        'USD',
        'Annual',
        100,
        75,
        -25,
        0,
        'Dec 19 - Nov 20',
        0,
        100,
        0,
        200,
        0,
        100,
        0,
        200,
        0,
        100,
        0,
        200,
        0,
        100,
        100,
      ],
      [
        'Totals',
        '',
        '',
        '',
        '',
        250,
        225,
        -25,
        500,
        '',
        100,
        200,
        150,
        100,
        200,
        150,
        100,
        200,
        150,
        100,
        200,
        150,
        100,
        200,
        2100,
      ],
      ['Currency', 'CAD', '$'],
      [
        'Partner',
        'Status',
        'Commitment Amount',
        'Commitment Currency',
        'Commitment Frequency',
        'Committed Monthly Equivalent',
        'In Hand Monthly Equivalent',
        'Missing In Hand Monthly Equivalent',
        'In Hand Special Gifts',
        'In Hand Date Range',
        'Mar 20',
        'Feb 20',
        'Jan 20',
        'Total (last month excluded from total)',
      ],
      ['Totals', '', '', '', '', 0, 0, 0, 0, '', 100, 200, 150, 450],
    ]);
  });
});
