export const info = {
  alma_mater: 'Sac State',
  anniversary_day: 23,
  anniversary_month: 6,
  anniversary_year: 1979,
  avatar:
    'https://lumiere-a.akamaihd.net/v1/images/ct_mickeymouseandfriends_mickey_ddt-16970_4e99445d.jpeg?region=0,0,600,600&width=480',
  birthday_day: 7,
  birthday_month: 10,
  birthday_year: 1983,
  email: [
    {
      value: 'personal@test.com',
      type: 'personal',
      primary: true,
      invalid: false,
    },
    {
      value: 'work@test.com',
      type: 'work',
      primary: false,
      invalid: true,
    },
  ],
  employer: 'Disney',
  facebook_accounts: ['CruGlobal', 'jplastow2'],
  family_relationships: [
    {
      name: 'Minnie',
      relation: 'Wife',
    },
    {
      name: 'Goofy',
      relation: 'Brother',
    },
  ],
  first_name: 'Mickey',
  gender: 'male',
  last_name: 'Mouse',
  legal_first_name: 'Michaelangelo',
  linkedin_accounts: ['https://www.linkedin.com/company/cru-global/'],
  marital_status: 'Married',
  middle_name: '',
  occupation: 'Head Mouse',
  parent_contacts: null,
  phone: [
    {
      value: '1234567890',
      type: 'home',
      primary: false,
      invalid: false,
    },
    {
      value: '0987654321',
      type: 'mobile',
      primary: true,
      invalid: false,
    },
  ],
  preferences: null,
  suffix: 'Sr.',
  title: 'Mr.',
  twitter_accounts: ['CruTweets'],
  websites: ['https://cru.org'],
};
