import React from 'react';
import { Container, Box } from '@material-ui/core';
import { motion } from 'framer-motion';
import { GetDashboardQuery } from '../../../../pages/accountLists/GetDashboard.generated';
import { MonthlyActivitySection } from './MonthlyActivitySection';
import { DonationsReportTable } from './DonationsReportTable';

interface Props {
  data: GetDashboardQuery;
  accountListId: string;
}

const variants = {
  animate: {
    transition: {
      delayChildren: 1,
      staggerChildren: 0.15,
    },
  },
  exit: {
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const DonationsReport: React.FC<Props> = ({ data, accountListId }) => {
  function createData(
    date: Date,
    partnerId: string,
    partner: string,
    currency: string,
    foreignCurrency: string,
    convertedAmount: number,
    foreignAmount: number,
    designation: string,
    method: string,
    id: string,
  ) {
    return {
      date,
      partnerId,
      partner,
      currency,
      foreignCurrency,
      convertedAmount,
      foreignAmount,
      designation,
      method,
      id,
    };
  }

  const rows = [
    createData(
      new Date(2018, 0, 0o5, 17, 23, 42, 11),
      'Bob',
      'Bob',
      'CAD',
      'USD',
      123.02,
      100,
      'You',
      'bank_trans',
      '1',
    ),
    createData(
      new Date(2019, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Joe',
      'CAD',
      'EUR',
      73.37,
      50,
      'You',
      'bank_trans',
      '2,',
    ),
    createData(
      new Date(2020, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Larry',
      'CAD',
      'CAD',
      2,
      2,
      'You',
      'bank_trans',
      '3',
    ),
    createData(
      new Date(2021, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Carl',
      'CAD',
      'CAD',
      234,
      234,
      'You',
      'bank_trans',
      '4',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Jared',
      'CAD',
      'CAD',
      55,
      55,
      'You',
      'bank_trans',
      '5',
    ) /*
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Luke',
      '354 CAD',
      '354 CAD',
      'You',
      'bank_trans',
      '6',
    ),
    createData(
      new Date(2016, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Bob',
      '100 CAD',
      '100 CAD',
      'You',
      'bank_trans',
      '12',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Joe',
      '34 CAD',
      '34 CAD',
      'You',
      'bank_trans',
      '22,',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Larry',
      '2 CAD',
      '2 CAD',
      'You',
      'bank_trans',
      '32',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Carl',
      '234 CAD',
      '234 CAD',
      'You',
      'bank_trans',
      '42',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Jared',
      '55 CAD',
      '55 CAD',
      'You',
      'bank_trans',
      '52',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Luke',
      '354 CAD',
      '354 CAD',
      'You',
      'bank_trans',
      '62',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Bob',
      '100 CAD',
      '100 CAD',
      'You',
      'bank_trans',
      '13',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Joe',
      '34 CAD',
      '34 CAD',
      'You',
      'bank_trans',
      '23,',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Larry',
      '2 CAD',
      '2 CAD',
      'You',
      'bank_trans',
      '33',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Carl',
      '234 CAD',
      '234 CAD',
      'You',
      'bank_trans',
      '43',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Jared',
      '55 CAD',
      '55 CAD',
      'You',
      'bank_trans',
      '53',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Luke',
      '354 CAD',
      '354 CAD',
      'You',
      'bank_trans',
      '63',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Bob',
      '100 CAD',
      '100 CAD',
      'You',
      'bank_trans',
      '14',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Joe',
      '34 CAD',
      '34 CAD',
      'You',
      'bank_trans',
      '25,',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Larry',
      '2 CAD',
      '2 CAD',
      'You',
      'bank_trans',
      '34',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Carl',
      '234 CAD',
      '234 CAD',
      'You',
      'bank_trans',
      '44',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Jared',
      '55 CAD',
      '55 CAD',
      'You',
      'bank_trans',
      '54',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Luke',
      '354 CAD',
      '354 CAD',
      'You',
      'bank_trans',
      '64',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Bob',
      '100 CAD',
      '100 CAD',
      'You',
      'bank_trans',
      '15',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Joe',
      '34 CAD',
      '34 CAD',
      'You',
      'bank_trans',
      '24,',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Larry',
      '2 CAD',
      '2 CAD',
      'You',
      'bank_trans',
      '35',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Carl',
      '234 CAD',
      '234 CAD',
      'You',
      'bank_trans',
      '45',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Jared',
      '55 CAD',
      '55 CAD',
      'You',
      'bank_trans',
      '55',
    ),
    createData(
      new Date(2018, 0o5, 0o5, 17, 23, 42, 11),
      'Bob',
      'Luke',
      '354 CAD',
      '354 CAD',
      'You',
      'bank_trans',
      '65',
    ),*/,
  ];
  return (
    <Box py={5}>
      <Container>
        <motion.div
          initial="initial"
          animate="animate"
          exit="exit"
          variants={variants}
        >
          <MonthlyActivitySection data={data} />
          <DonationsReportTable data={rows} accountListId="abc" />
        </motion.div>
      </Container>
    </Box>
  );
};
