export const geographicAdjustments = new Map<string, number>([
  ['None', 0],
  ['Amherst, MA', 0.23],
  ['Anchorage, AK', 0.33],
  ['Atlanta, GA', 0.12],
  ['Austin, TX', 0.07],
  ['Beaufort, SC', 0.06],
  ['Bellingham, WA', 0.2],
  ['Bend, OR', 0.21],
  ['Berkeley, CA', 0.49],
  ['Boston, MA', 0.61],
  ['Boulder, CO', 0.17],
  ['Bozeman, MT', 0.25],
  ['Buffalo, NY', 0.07],
  ['Burlington, VT', 0.25],
  ['Chapel Hill, NC', 0.05],
  ['Charleston, SC', 0.07],
  ['Charlottesville, VA', 0.1],
  ['Chicago, IL', 0.26],
  ['Chico, CA', 0.28],
  ['Clovis, CA', 0.21],
  ['Colorado Springs, CO', 0.06],
  ['Corvallis, OR', 0.2],
  ['Davis, CA', 0.33],
  ['Denver, CO', 0.25],
  ['Eugene, OR', 0.16],
  ['Fort Collins, CO', 0.09],
  ['Honolulu, HI', 0.85],
  ['Hilo, HI', 0.87],
  ['Los Angeles, CA', 0.63],
  ['Long Beach, CA', 0.63],
  ['Manchester, NH', 0.22],
  ['Miami, FL', 0.21],
  ['Minneapolis, MN', 0.15],
  ['Monterey, CA', 0.32],
  ['Naples, FL', 0.18],
  ['New Haven, CT', 0.23],
  ['New York City', 0.83],
  ['Newark, NJ', 0.28],
  ['Orange Co, CA', 0.58],
  ['Orlando, FL', 0.06],
  ['Philadelphia, PA', 0.28],
  ['Phoenix, AZ', 0.17],
  ['Plano, TX', 0.09],
  ['Portland, ME', 0.23],
  ['Portland, OR', 0.27],
  ['Providence, RI', 0.2],
  ['Riverside, CA', 0.58],
  ['Sacramento, CA', 0.36],
  ['Salt Lake City, UT', 0.1],
  ['San Diego, CA', 0.47],
  ['San Francisco, CA', 1.01],
  ['San Jose, CA', 0.84],
  ['San Luis Obispo, CA', 0.34],
  ['Santa Barbara, CA', 0.35],
  ['Seattle, WA', 0.35],
  ['Washington, D.C.', 0.59],
  ['West Chester, PA', 0.16],
]);

export const locations = geographicAdjustments.keys().toArray();
