export const activitySummaryMocks = {
  reportsActivityResults: {
    periods: [
      {
        startDate: '2023-06-02',
        endDate: '2023-06-07',
        appointmentInPerson: 1,
        followUpPhoneCall: 2,
        partnerCareThank: 3,
        initiationSocialMedia: 4,
        appointmentTotal: 5,
        initiationTotal: 6,
        partnerCareDigitalNewsletter: 77,
        followUpTextMessage: 8,
        contactsAdded: 30,
        contactsReferred: 8,
      },
      {
        startDate: '2023-05-02',
        endDate: '2023-05-07',
        appointmentInPerson: 1,
        followUpPhoneCall: 2,
        partnerCareThank: 3,
        initiationSocialMedia: 4,
        appointmentTotal: 5,
        initiationTotal: 6,
        partnerCareDigitalNewsletter: 77,
        followUpTextMessage: 8,
        contactsAdded: 30,
        contactsReferred: 8,
      },
      {
        startDate: '2023-04-02',
        endDate: '2023-04-07',
        appointmentInPerson: 11,
        followUpPhoneCall: 12,
        partnerCareThank: 13,
        initiationSocialMedia: 14,
        appointmentTotal: 15,
        initiationTotal: 16,
        partnerCareDigitalNewsletter: 97,
        followUpTextMessage: 18,
        contactsAdded: 40,
        contactsReferred: 5,
      },
      {
        startDate: '2023-03-02',
        endDate: '2023-03-07',
        appointmentInPerson: 31,
        followUpPhoneCall: 32,
        partnerCareThank: 33,
        initiationSocialMedia: 34,
        appointmentTotal: 35,
        initiationTotal: 36,
        partnerCareDigitalNewsletter: 107,
        followUpTextMessage: 38,
        contactsAdded: 50,
        contactsReferred: 7,
      },
    ],
  },
};

export const appointmentResultsMocks = {
  appointmentResults: [
    {
      startDate: '2023-09-02',
      endDate: '2023-09-04',
      appointmentsScheduled: 6,
      individualAppointments: 7,
      newMonthlyPartners: 1,
      newSpecialPledges: 2,
      monthlyIncrease: 111.11,
      monthlyDecrease: -222.22,
      specialGifts: 333.33,
    },
    {
      startDate: '2023-10-02',
      endDate: '2023-10-04',
      appointmentsScheduled: 8,
      individualAppointments: 9,
      newMonthlyPartners: 2,
      newSpecialPledges: 3,
      monthlyIncrease: 666.66,
      monthlyDecrease: -444.44,
      specialGifts: 555.55,
    },
    {
      startDate: '2023-11-02',
      endDate: '2023-11-04',
      appointmentsScheduled: 11,
      individualAppointments: 12,
      newMonthlyPartners: 4,
      newSpecialPledges: 5,
      monthlyIncrease: 777.77,
      monthlyDecrease: -888.88,
      specialGifts: 999.99,
    },
  ],
};
