query Hcm(
  $effectiveDate: ISO8601Date
  $personNumber: String
  $refresh: Boolean
) {
  hcm(
    effectiveDate: $effectiveDate
    personNumber: $personNumber
    refresh: $refresh
  ) {
    syncedAt
    outOfSync
    usStaffGroup
    staffInfo {
      id
      preferredName
      lastName
      personNumber
      emailAddress
      primaryPhoneNumber
      age
      addressLine1
      addressLine2
      city
      country
      state
      zipCode
      dependentChildrenWithHealthcareBenefits
      isInternational
      secaStatus
      tenure
      peopleGroupSupportType
      userPersonType
      assignmentStatus
      assignmentCategory
    }
    currentSalary {
      grossSalaryAmount
      lastRegularPaymentDate
      lastUpdated
    }
    exceptionSalaryCap {
      amount
      effectiveDate
    }
    fourOThreeB {
      currentRothContributionPercentage
      currentTaxDeferredContributionPercentage
      maximumContributionLimit
      fourOThreeBMakeUpLimitAmount
    }
    mhaEit {
      mhaEligibility
      ineligibilityReasonCode
    }
    mhiEit {
      mhiEligibility
      ineligibilityReasonCode
    }
    asrEit {
      asrEligibility
      ineligibilityReason
    }
    mhaRequest {
      currentApprovedOverallAmount
      currentTakenAmount
      boardApprovedOnDate
    }
    salaryRequestEligible
    designationSupportCalculatorEligible
  }
}
