export const mocks = {
  PartnerGivingAnalysis: {
    partnerGivingAnalysis: {
      nodes: [
        {
          id: '01',
          name: 'Flintstone, Fred and Wilma',
          totalDonations: 49835,
          pledgeCurrency: 'USD',
          lastDonationDate: '2022-04-12',
          lastDonationAmount: 3000,
          lastDonationCurrency: 'INR',
          donationPeriodAverage: 1215.4878048780488,
          donationPeriodCount: 41,
          donationPeriodSum: 49835,
        },
        {
          id: '02',
          name: 'Mouse, Mickey and Minnie',
          totalDonations: 2175,
          pledgeCurrency: 'USD',
          lastDonationDate: '2020-12-15',
          lastDonationAmount: 75,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 80.55555555555556,
          donationPeriodCount: 27,
          donationPeriodSum: 2175,
        },
        {
          id: '03',
          name: 'Pan, Peter and Wendy',
          totalDonations: 1045,
          pledgeCurrency: 'USD',
          lastDonationDate: '2020-12-15',
          lastDonationAmount: 30,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 37.32142857142857,
          donationPeriodCount: 28,
          donationPeriodSum: 1045,
        },
        {
          id: '04',
          name: 'Pooh, Winnie',
          totalDonations: 255,
          pledgeCurrency: 'USD',
          lastDonationDate: '2019-10-05',
          lastDonationAmount: 10,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 10.625,
          donationPeriodCount: 24,
          donationPeriodSum: 255,
        },
        {
          id: '05',
          name: 'Dalmation, Pongo and Perdita',
          totalDonations: 41250,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-07-11',
          lastDonationAmount: 200,
          lastDonationCurrency: 'UGX',
          donationPeriodAverage: 982.1428571428571,
          donationPeriodCount: 42,
          donationPeriodSum: 41250,
        },
        {
          id: '06',
          name: 'Deer, Bambi and Feline',
          totalDonations: 24795,
          pledgeCurrency: 'UGX',
          lastDonationDate: '2022-01-12',
          lastDonationAmount: 12000,
          lastDonationCurrency: 'INR',
          donationPeriodAverage: 918.3333333333334,
          donationPeriodCount: 27,
          donationPeriodSum: 24796,
        },
        {
          id: '07',
          name: 'Duck, Daffy and Daphney',
          totalDonations: 11039,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-07-11',
          lastDonationAmount: 200,
          lastDonationCurrency: 'UGX',
          donationPeriodAverage: 356.0967741935484,
          donationPeriodCount: 31,
          donationPeriodSum: 11039,
        },
        {
          id: '08',
          name: 'Jetson, George and Jane',
          totalDonations: 1160,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-07-09',
          lastDonationAmount: 200,
          lastDonationCurrency: 'UGX',
          donationPeriodAverage: 46.422,
          donationPeriodCount: 25,
          donationPeriodSum: 1160,
        },
        {
          id: '09',
          name: 'Beast, Beast and Belle',
          totalDonations: 1400,
          pledgeCurrency: 'ARM',
          lastDonationDate: '2025-07-22',
          lastDonationAmount: 200,
          lastDonationCurrency: 'UGX',
          donationPeriodAverage: 466.6666666666667,
          donationPeriodCount: 3,
          donationPeriodSum: 1400,
        },
        {
          id: '10',
          name: 'Duck, Donald and Daisy',
          totalDonations: 333336588,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-07-02',
          lastDonationAmount: 1000,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 10752793.161290323,
          donationPeriodCount: 31,
          donationPeriodSum: 333336588,
        },
        {
          id: '11',
          name: 'First Pedestrian Church',
          totalDonations: 14733,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-07-16',
          lastDonationAmount: 200,
          lastDonationCurrency: 'UGX',
          donationPeriodAverage: 475.28225806451616,
          donationPeriodCount: 31,
          donationPeriodSum: 14733,
        },
        // i need to get 25 total entries
        {
          id: '12',
          name: 'Hero, Hercules and Megara',
          totalDonations: 8900,
          pledgeCurrency: 'USD',
          lastDonationDate: '2024-05-10',
          lastDonationAmount: 150,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 295.8333333333333,
          donationPeriodCount: 30,
          donationPeriodSum: 8900,
        },
        {
          id: '13',
          name: 'Lion, Simba and Nala',
          totalDonations: 12345,
          pledgeCurrency: 'USD',
          lastDonationDate: '2023-11-20',
          lastDonationAmount: 250,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 411.5,
          donationPeriodCount: 30,
          donationPeriodSum: 12345,
        },
        {
          id: '14',
          name: 'Nemo, Marlin and Dory',
          totalDonations: 6789,
          pledgeCurrency: 'USD',
          lastDonationDate: '2022-08-15',
          lastDonationAmount: 100,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 226.3,
          donationPeriodCount: 30,
          donationPeriodSum: 6789,
        },
        {
          id: '15',
          name: 'Olaf, Anna and Elsa',
          totalDonations: 2345,
          pledgeCurrency: 'USD',
          lastDonationDate: '2021-12-05',
          lastDonationAmount: 75,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 78.16666666666667,
          donationPeriodCount: 30,
          donationPeriodSum: 2345,
        },
        {
          id: '16',
          name: 'Peter Rabbit and Friends',
          totalDonations: 4567,
          pledgeCurrency: 'USD',
          lastDonationDate: '2020-09-25',
          lastDonationAmount: 125,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 152.33333333333334,
          donationPeriodCount: 30,
          donationPeriodSum: 4567,
        },
        {
          id: '17',
          name: 'Quasimodo and Esmeralda',
          totalDonations: 3456,
          pledgeCurrency: 'USD',
          lastDonationDate: '2019-06-30',
          lastDonationAmount: 90,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 115.2,
          donationPeriodCount: 30,
          donationPeriodSum: 3456,
        },
        {
          id: '18',
          name: 'Robin Hood and Maid Marian',
          totalDonations: 7890,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-01-18',
          lastDonationAmount: 200,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 263,
          donationPeriodCount: 30,
          donationPeriodSum: 7890,
        },
        {
          id: '19',
          name: 'Stitch and Lilo',
          totalDonations: 2340,
          pledgeCurrency: 'USD',
          lastDonationDate: '2024-03-22',
          lastDonationAmount: 80,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 78,
          donationPeriodCount: 30,
          donationPeriodSum: 2340,
        },
        {
          id: '20',
          name: 'Tarzan and Jane',
          totalDonations: 5678,
          pledgeCurrency: 'USD',
          lastDonationDate: '2023-07-14',
          lastDonationAmount: 150,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 189.26666666666668,
          donationPeriodCount: 30,
          donationPeriodSum: 5678,
        },
        {
          id: '21',
          name: 'Ursula and Ariel',
          totalDonations: 3450,
          pledgeCurrency: 'USD',
          lastDonationDate: '2022-11-11',
          lastDonationAmount: 100,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 115,
          donationPeriodCount: 30,
          donationPeriodSum: 3450,
        },
        {
          id: '22',
          name: 'VeggieTales Crew',
          totalDonations: 1234,
          pledgeCurrency: 'USD',
          lastDonationDate: '2021-05-05',
          lastDonationAmount: 50,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 41.13333333333333,
          donationPeriodCount: 30,
          donationPeriodSum: 1234,
        },
        {
          id: '23',
          name: 'Winnie the Pooh and Friends',
          totalDonations: 678,
          pledgeCurrency: 'USD',
          lastDonationDate: '2020-02-20',
          lastDonationAmount: 30,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 22.6,
          donationPeriodCount: 30,
          donationPeriodSum: 678,
        },
        {
          id: '24',
          name: 'X-Men',
          totalDonations: 91011,
          pledgeCurrency: 'USD',
          lastDonationDate: '2019-12-12',
          lastDonationAmount: 3000,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 3033.7,
          donationPeriodCount: 30,
          donationPeriodSum: 91011,
        },
        {
          id: '25',
          name: 'Yogi Bear and Boo-Boo',
          totalDonations: 345,
          pledgeCurrency: 'USD',
          lastDonationDate: '2025-06-06',
          lastDonationAmount: 15,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 11.5,
          donationPeriodCount: 30,
          donationPeriodSum: 345,
        },
        {
          id: '26',
          name: 'Zootopia Residents',
          totalDonations: 78901,
          pledgeCurrency: 'USD',
          lastDonationDate: '2024-10-10',
          lastDonationAmount: 2500,
          lastDonationCurrency: 'USD',
          donationPeriodAverage: 2630.0333333333333,
          donationPeriodCount: 30,
          donationPeriodSum: 78901,
        },
      ],
      pageInfo: {
        endCursor: 'MTg',
        hasNextPage: false,
        hasPreviousPage: false,
      },
      edges: [
        { cursor: 'OA' },
        { cursor: 'OQ' },
        { cursor: 'MTA' },
        { cursor: 'MTE' },
        { cursor: 'MTI' },
        { cursor: 'MTM' },
        { cursor: 'MTQ' },
        { cursor: 'MTU' },
        { cursor: 'MTY' },
        { cursor: 'MTc' },
        { cursor: 'MTA' },
        { cursor: 'MTk' },
        { cursor: 'MjA' },
        { cursor: 'MjE' },
        { cursor: 'MjI' },
        { cursor: 'MjM' },
        { cursor: 'MjQ' },
        { cursor: 'MjU' },
        { cursor: 'MjY' },
        { cursor: 'Mjc' },
        { cursor: 'Mjg' },
        { cursor: 'Mjk' },
        { cursor: 'MzA' },
        { cursor: 'MzE' },
        { cursor: 'MzI' },
        { cursor: 'MTg' },
      ],
      totalCount: 26,
      totalPageCount: 1,
    },
  },
  GetPartnerGivingAnalysisIdsForMassSelection: {
    partnerGivingAnalysis: {
      nodes: [
        { id: '01' },
        { id: '02' },
        { id: '03' },
        { id: '04' },
        { id: '05' },
        { id: '06' },
        { id: '07' },
        { id: '08' },
        { id: '09' },
        { id: '10' },
        { id: '11' },
        { id: '12' },
        { id: '13' },
        { id: '14' },
        { id: '15' },
        { id: '16' },
        { id: '17' },
        { id: '18' },
        { id: '19' },
        { id: '20' },
        { id: '21' },
        { id: '22' },
        { id: '23' },
        { id: '24' },
        { id: '25' },
        { id: '26' },
      ],
    },
  },
};
