name: Merge PR into staging
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'On Staging')
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: 'staging'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
